config/routes.rb
Needsapp2::Application.routes.draw do

  root :to => "sessions#new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"


  resources :users
  resources :slots
  resources :sessions

  #Commented out showing needs per category
  #Instead we use a combined search operation
  resources :categories # do
  #  member do
  #    get :needs
  #  end
  #end

  resources :needs do
    collection do
      get :search
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :password_confirmation, :admin, :label

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password

  def self.authenticate(password)
    if user = User.find_by_password_hash(BCrypt::Engine.hash_secret(password, '$2a$10$Ch9fWSFHEz72UeHz5d0CeO'))
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      #Hardcoding a salt is a really bad idea - but I think password hashing alone is sufficient for this app
      #Allows us to authenticate using only a password and not a username
      self.password_hash = BCrypt::Engine.hash_secret(password, '$2a$10$Ch9fWSFHEz72UeHz5d0CeO')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_admin

  def authenticate_admin
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    if !@current_user && !@current_user.admin
      redirect_to root_url, :notice => "You must be logged in and have permission to do that!"
      return
    end
  end

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to '/users', :notice => "Created user"
	  else
	    render "new"
	  end
	end

	  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

   def update
    @user = User.find(params[:id])

    if @user.admin && @current_user.id != 1
      redirect_to '/users', :notice => "Only user 1 may edit admins!"
      return
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == 1
      redirect_to users_url, :notice => "You can't delete user 1"
      return
    end

    if @user.admin && @current_user.id != 1
      redirect_to users_url, :notice => "Only user 1 may delete admins!"
      return
    end

    @user.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: 'user was removed.' }
    end
  end

   def edit
    @user = User.find(params[:id])

    #protect user #1 and admins
    if @user.id != @current_user.id && @current_user.id != 1
      redirect_to users_url, :notice => "Only user 1 may edit other admins!"
      return
    end

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.submit 'Update User', :class=>'btn submit btn-info'  %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>User Management</h1>

<table>
  <tr>
    <th>User</th>
    <th>Label</th>
    <th>Admin</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.label %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit 'Create User', :class=>'btn submit btn-info'  %>
  </div>
<% end %>