config/routes.rb
Needsapp2::Application.routes.draw do

  root :to => "sessions#new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"


  resources :users
  resources :slots
  resources :sessions

  #Commented out showing needs per category
  #Instead we use a combined search operation
  resources :categories # do
  #  member do
  #    get :needs
  #  end
  #end

  resources :needs do
    collection do
      get :search
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :needs
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate

  def authenticate
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    if !@current_user || !@current_user.admin
      redirect_to needs_url, :notice => "You must be logged in and have permission to do that!"
      return
    end
  end

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end

  #For showing all needs that belong to a cateory - not used in final app
  #def needs
    #@category = Category.find(params[:id])
    #@needs = @category.needs
  #end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc, "Description" %>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-info'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Category Management</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/needs.html.erb
<%# This view is used for nested attributes - it is not used in the final app, but is another way to present needs that belong to a certain category %>

<% body_id 'index' %>
<% body_class 'needs' %>

<% if @needs.first %>
  <% @needs.each do |need| %>
    <div class="need">
      <%= form_for(need) do |form| %>
      <div class="category">
        <span class="label"><%= need.category.title unless need.category.blank? %></span>
      </div>
      <div class="slots">
        <h5>Sign Up to Help</h5>
        <%= form.fields_for :slots do |slot| %>
          <div class ="slot">
            <div class = "note"><%= slot.object.note %></div>
            <% if slot.object.name %>
              <%= slot.text_field :name, :readOnly => 'true', :class=> 'text' %>
            <% else %>
              <%= slot.text_field :name, :class=> 'text' %>
              <%= form.submit 'Sign Up', :class => 'btn' %>
            <% end %>
          </div>
        <% end %>
        </div>
      <% end %>
      <h3 class="title"><%= link_to need.title, edit_need_path(need) %></h3>
      <div class="date"><%= need.date.strftime('%Y-%m-%d') %>
        <% if need.time1 > '' %>
          <span class="time"> - <%= need.time1 %>:<%= need.time2 %> <%= need.time3 %></span>
        <% end %>
      </div>
      <div class="desc"><%= need.desc %></div>
    </div>
  <% end %>
<% else %>
  <div>No needs matched your search</div>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>